server:
   port: ${PORT:8080}
application:
   name: ^project.artifactId^
   description: ^project.name^
   version: ^project.version^
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/category/**
          name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/category
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/product

feign:
  hystrix:
    enabled=true

logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: info
    org.springframework.web.reactive: debug
    reactor.ipc.netty: info


remote:
  category: http://${CATEGORYSERVICE_HOST:localhost}:8081
  product: http://${PRODUCTSERVICE_HOST:localhost}:8082

