server:
  port: ${CATEGORYSERVICE_PORT:8081}
application:
  name: ^project.artifactId^
  description: ^project.name^
  version: ^project.version^

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: category-service
  profiles:
    active: dev
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      database: category-service
      auto-index-creation: true
      username: user
      password: password
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

info:
  version: ${project.version}

management:
  endpoint:
    shutdown:
      enabled: true

#logging.level:
#  com.hes24: TRACE

logging:
  level:
    org.springframework.web: DEBUG
    com.satish.monitoring: DEBUG

fixer:
#  api-key: 'put here your key'
  api-key: '5c2f8a74aabb5672df5505dafad942e0'
  url: 'http://data.fixer.io'

feign:
  hystrix:
    enabled=true

